version: '3'

services:
  mongo:
    image: mongo:latest
    env_file:
      - ./RankingMaster.env
    ports:
      - "27017:27017"
  python_replay:
    build: ReplayService
    ports:
     - "5000:5000"
    volumes:
     - ./ReplayService/uploads:/app/uploads
  ranking_master:
    build: RankingMaster
    env_file:
      - ./RankingMaster.env
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
    links:
      - "mongo:database"
