import React, { Component } from 'react';
import { GridGenerator, HexGrid, Layout, Path, Hexagon, Text, Pattern, Hex } from 'react-hexgrid';
import './App.css';

class App extends Component {

  render() {
    var hexagons = GridGenerator.hexagon(7);

    console.log(hexagons[0]);
    hexagons.splice(142, 27);

    const images = [
      "",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Aatrox.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ahri.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Akali.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Alistar.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Amumu.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Anivia.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Annie.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ashe.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/AurelionSol.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Azir.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Bard.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Blitzcrank.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Brand.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Braum.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Caitlyn.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Camille.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Cassiopeia.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Chogath.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Corki.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Darius.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Diana.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/DrMundo.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Draven.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ekko.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Elise.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Evelynn.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ezreal.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Fiddlesticks.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Fiora.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Fizz.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Galio.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Gangplank.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Garen.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Gnar.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Gragas.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Graves.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Hecarim.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Heimerdinger.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Illaoi.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Irelia.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ivern.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Janna.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/JarvanIV.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Jax.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Jayce.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Jhin.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Jinx.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kaisa.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kalista.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Karma.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Karthus.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kassadin.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Katarina.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kayle.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kayn.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kennen.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Khazix.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kindred.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Kled.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/KogMaw.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Leblanc.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/LeeSin.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Leona.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Lissandra.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Lucian.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Lulu.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Lux.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Malphite.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Malzahar.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Maokai.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/MasterYi.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/MissFortune.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Mordekaiser.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Morgana.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Nami.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Nasus.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Nautilus.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Nidalee.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Nocturne.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Nunu.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Olaf.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Orianna.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ornn.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Pantheon.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Poppy.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Pyke.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Quinn.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Rakan.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Rammus.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/RekSai.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Renekton.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Rengar.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Riven.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Rumble.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ryze.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Sejuani.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Shaco.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Shen.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Shyvana.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Singed.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Sion.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Sivir.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Skarner.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Sona.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Soraka.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Swain.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Syndra.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/TahmKench.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Taliyah.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Talon.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Taric.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Teemo.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Thresh.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Tristana.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Trundle.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Tryndamere.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/TwistedFate.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Twitch.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Udyr.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Urgot.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Varus.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Vayne.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Veigar.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Velkoz.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Vi.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Viktor.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Vladimir.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Volibear.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Warwick.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/MonkeyKing.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Xayah.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Xerath.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/XinZhao.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Yasuo.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Yorick.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Zac.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Zed.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Ziggs.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Zilean.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Zoe.png",
      "https://ddragon.leagueoflegends.com/cdn/8.22.1/img/champion/Zyra.png"
    ];

    const champions = ["empty", "Aatrox", "Ahri", "Akali", "Alistar", "Amumu", "Anivia", "Annie", "Ashe", "Aurelion Sol", "Azir", "Bard",
    "Blitzcrank", "Brand", "Braum", "Caitlyn", "Camille", "Cassiopeia", "Cho'Gath", "Corki", "Darius", "Diana", "Dr. Mundo", "Draven",
    "Ekko", "Elise", "Evelynn", "Ezreal", "Fiddlesticks", "Fiora", "Fizz", "Galio", "Gangplank", "Garen", "Gnar", "Gragas", "Graves",
    "Hecarim", "Heimerdinger", "Illaoi", "Irelia", "Ivern", "Janna", "Jarvan IV", "Jax", "Jayce", "Jhin", "Jinx", "Kai'Sa", "Kalista",
    "Karma", "Karthus", "Kassadin", "Katarina", "Kayle", "Kayn", "Kennen", "Kha'Zix", "Kindred", "Kled", "Kog'Maw", "LeBlanc", "Lee Sin",
    "Leona", "Lissandra", "Lucian", "Lulu", "Lux", "Malphite", "Malzahar", "Maokai", "Master Yi", "Miss Fortune", "Mordekaiser", "Morgana",
    "Nami", "Nasus", "Nautilus", "Nidalee", "Nocturne", "Nunu & Willump", "Olaf", "Orianna", "Ornn", "Pantheon", "Poppy", "Pyke", "Quinn",
    "Rakan", "Rammus", "Rek'Sai", "Renekton", "Rengar", "Riven", "Rumble", "Ryze", "Sejuani", "Shaco", "Shen", "Shyvana", "Singed", "Sion",
    "Sivir", "Skarner", "Sona", "Soraka", "Swain", "Syndra", "Tahm Kench", "Taliyah", "Talon", "Taric", "Teemo", "Thresh", "Tristana", "Trundle",
    "Tryndamere", "Twisted Fate", "Twitch", "Udyr", "Urgot" , "Varus", "Vayne", "Veigar", "Vel'Koz", "Vi", "Viktor", "Vladimir", "Volibear",
    "Warwick", "Wukong", "Xayah", "Xerath", "Xin Zhao", "Yasuo", "Yorick", "Zac", "Zed", "Ziggs", "Zilean", "Zoe", "Zyra"];

    return (
      <div className="App">
        <h1>LoL App</h1>
        <HexGrid width={1200} height={1000}>
          <Layout size={{ x: 4, y: 4 }}>
            { hexagons.map((hex, i) => <Hexagon fill={i} key={i} q={hex.q} r={hex.r} s={hex.s}><Text>{i}</Text></Hexagon>) }
          </Layout>
          { images.map((champion, i) => <Pattern id={i} link={champion} size={{ x: 4, y: 4 }} />) }
        </HexGrid>
      </div>
    );
  }
}

export default App;
